# Generated by Django 2.2.5 on 2020-01-17 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_pass', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]{1}[0-9]{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
