# Generated by Django 2.2.5 on 2020-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='entry_pass',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
