# Generated by Django 3.0.2 on 2020-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200117_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('counter', models.PositiveIntegerField()),
            ],
        ),
    ]
