# Generated by Django 3.0.2 on 2020-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='counter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
