# Generated by Django 3.0.2 on 2020-02-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200221_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
