# Generated by Django 3.0.2 on 2020-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_attendee_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
